### ISSUE TITLE
Source code question

### ISSUE THREAD

**Issue by andrewpbray** [syanco/seasonal_survival#1]
Hello! I just came across [this paper](https://www.nature.com/articles/s41559-024-02545-y) and I love it. Fascinating research question and terrific experimental setup. I teach statistics in the US and was considering using this paper in my classes. I was delighted to find a link to a GitHub repo in the paper, however, that link seemed to be broken. I came to this repo as the most recently active one in hopes that you could point me in the right direction.

Thanks!

**Comment by syanco** [comment]
Thanks for your interest and good catch! I failed to make that repo public on Wednesday when the paper came out. It's status is now changed and the link (https://github.com/syanco/blackbird_metabolics) should now work. Please note that that repo is only for the biophysical modeling portions of the paper.  Please feel to reach out to me if you have any questions about running it. 

I'll close out this issue but feel free to reach out again via email or issue on that repo.

-Scott
